import 'package:portfolio_website/constants/image_constants.dart';
import 'package:portfolio_website/constants/url_constants.dart';
import 'package:portfolio_website/model/individual_project_model.dart';

class IndividualProjectGenerator {
  static int workedProjectLength = generateWorkedProject().length;
  static List<IndividualProject> generateWorkedProject() {
    return [
      IndividualProject(
        id: 1,
        image: ImageConstant.imgAppIconPerr2,
        projectName: "Perr",
        projectSubTitle: "Flutter | Firebase",
        iosIcon: ImageConstant.svgIos,
        iosAppLink: LaunchAppsProjectURL.iosLinkPerr,
        androidIcon: ImageConstant.svgAndroid,
        androidAppLink: LaunchAppsProjectURL.androidLinkPerr,
        githubIcon: ImageConstant.svgGithub,
        githubProjectLink: null,
        listofScreenshot: [
          "1.PNG",
          "2.PNG",
          "3.PNG",
          "4.PNG",
          "5.PNG",
          "6.PNG",
          "7.PNG",
          "8.PNG",
          "9.PNG",
          "10.PNG",
          "11.PNG",
          "12.PNG",
          "13.PNG",
          "14.PNG",
          "15.PNG",
          "16.PNG",
        ],
        screenshotFolderName: "perr",
        aboutTheProject:
            "Perr is a user-friendly file-sharing application that allows users to effortlessly share various files, including those from their gallery, files, and URLs. Send photos, videos, documents, and more without any hassle between PC and mobile devices (iOS and Android). There's no need for cumbersome emailing or messaging files to yourself—simply scan the code and transfer them seamlessly between multiple devices, whether from phone to PC or vice versa. You can even share your documents using the Share Extension on your phone. The 'Trusted Devices' feature enables a one-time sign-in for easy file sharing between frequently used devices.",
        techStack:
            "Flutter, Swift, REST API Integration, Firebase Integration, Responsive Design, Visual Studio Code, BloC, GetX, Google/Apple sign-in, Swagger UI, Sockets, Flavors, Pagination",
      ),
      IndividualProject(
        id: 2,
        image: ImageConstant.imgAppIconTechnicalTalent,
        projectName: "Technical Talent",
        projectSubTitle: "Flutter | Firebase",
        iosIcon: ImageConstant.svgIos,
        iosAppLink: LaunchAppsProjectURL.iosLinkTechnicalTalent,
        androidIcon: ImageConstant.svgAndroid,
        androidAppLink: LaunchAppsProjectURL.androidLinkTechnicalTalent,
        githubIcon: ImageConstant.svgGithub,
        githubProjectLink: null,
        listofScreenshot: [
          "1.PNG",
          "2.PNG",
          "3.PNG",
          "4.PNG",
          "5.PNG",
          "6.PNG",
          "7.PNG",
          "8.PNG",
          "9.PNG",
          "10.PNG",
          "11.PNG",
          "12.PNG",
          "13.PNG",
        ],
        screenshotFolderName: "technical_talent",
        aboutTheProject:
            "Technical Talent is a dynamic marketplace application designed to connect individuals with job opportunities in the audio, video, lighting, and stage industries, specifically within the Music Industry. Tailored for professionals seeking freelance gigs, part-time roles, or full-time employment, this platform serves as a centralized hub for employers and skilled individuals to collaborate seamlessly. With the In-App Purchases feature built-in, creating a new job automatically triggers an invitation. Stay informed about new job listings, messages, and updates through real-time push notifications. Engage in real-time communication with potential employers and other talents using the in-app chat feature.",
        techStack:
            "Flutter, REST API Integration, In-App Purchase, Stripe, Firebase Integration, Push Notification, Dynamic Link, One-to-One chat feature using Firestore Database, GetX, Flavors, Responsive Design, Visual Studio Code",
      ),
      IndividualProject(
        id: 3,
        image: ImageConstant.imgAppIconRayy,
        projectName: "Rayy",
        projectSubTitle: "Flutter | Firebase",
        iosIcon: ImageConstant.svgIos,
        iosAppLink: null,
        androidIcon: ImageConstant.svgAndroid,
        androidAppLink: null,
        githubIcon: ImageConstant.svgGithub,
        githubProjectLink: null,
        listofScreenshot: [
          "1.PNG",
          "2.PNG",
          "3.PNG",
          "4.PNG",
          "5.PNG",
          "6.PNG",
          "7.PNG",
          "8.PNG",
          "9.PNG",
          "10.PNG",
          "11.PNG",
          "12.PNG",
          "13.PNG",
          "14.PNG",
          "15.PNG",
          "16.PNG",
          "17.PNG",
          "18.PNG",
          "19.PNG",
          "20.PNG",
          "21.PNG",
        ],
        screenshotFolderName: "rayy",
        aboutTheProject:
            "Rayy is an innovative e-commerce application that rewards you for every purchase. Its main motto is 'shop and get rewards,' where users receive real-time push notifications about their earned rewards. Additionally, referring others brings extra rewards, especially if your referred contact shares the same location. The homepage allows you to select your location, and if it matches with your referral, you receive a special bonus. Enjoy browsing through different offers displayed on the homepage, featuring a dynamic carousel with a shimmer effect.",
        techStack:
            "Flutter, Visual Studio Code, Responsive Design, REST API Integration, Location using Google API, Firebase Integration,Swagger UI, Google/Apple sign-in,GetX",
      ),
      IndividualProject(
        id: 4,
        image: ImageConstant.imgAppIconXchange,
        projectName: "Xchange",
        projectSubTitle: "Flutter | Node.js | Flask",
        iosIcon: ImageConstant.svgIos,
        iosAppLink: LaunchAppsProjectURL.iosLinkXchange,
        androidIcon: ImageConstant.svgAndroid,
        androidAppLink: LaunchAppsProjectURL.androidLinkXchange,
        githubIcon: ImageConstant.svgGithub,
        githubProjectLink: LaunchAppsProjectURL.githubLinkXchange,
        listofScreenshot: [
          "1.png",
          "2.png",
          "3.png",
          "4.png",
          "5.png",
          "6.png",
          "7.png",
          "8.png",
          "9.png",
          "10.png",
          "11.png",
          "12.png",
          "13.png",
          "14.png",
          "15.png",
          "16.png",
          "17.png",
          "18.png",
          "19.png",
          "20.png",
          "21.png",
          "22.png",
          "23.png",
          "24.png",
          "25.png",
          "26.png",
          "27.png",
          "28.png",
          "29.png",
          "30.png",
          "31.png",
        ],
        screenshotFolderName: "xchange",
        aboutTheProject:
            "Xchange is a classified marketplace application where users can sell any products they want, and buyers can purchase the listed items. Additionally, buyers will receive a list of recommended products based on user ratings and liked items.",
        techStack:
            "Flutter, Node.js, Flask, Machine Learning, Recommendation, Figma, UI/UX, Responsive Design, Pixel-Perfect Design, Wireframe, Visual Studio Code, ",
      ),
      IndividualProject(
        id: 5,
        image: ImageConstant.imgAppIconHamroBank,
        projectName: "Hamro Bank",
        projectSubTitle: "Flutter",
        iosIcon: ImageConstant.svgIos,
        iosAppLink: null,
        androidIcon: ImageConstant.svgAndroid,
        androidAppLink: null,
        githubIcon: ImageConstant.svgGithub,
        githubProjectLink: LaunchAppsProjectURL.githubLinkHamroBank,
        listofScreenshot: [
          "1.png",
          "2.png",
          "3.png",
          "4.png",
          "5.png",
          "6.png",
          "7.png",
          "8.png",
          "9.png",
          "10.png",
          "11.png",
          "12.png",
          "13.png",
          "14.png",
          "15.png",
          "16.png",
        ],
        screenshotFolderName: "hamro_bank",
        aboutTheProject:
            "Hamro Bank is a banking application that I developed during my learning phase of Flutter. Initially, I designed the entire concept and UI/UX using Figma, and then I hard-coded the application with Flutter, adhering to a pixel-perfect design pattern.",
        techStack:
            "Flutter, Figma, UI/UX, Responsive Design, Pixel-Perfect Design, Wireframe, Visual Studio Code",
      ),
    ];
  }
}
